
package co.edu.usbcali.presentation.businessDelegateWS.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.10
 * Sun Mar 30 13:13:47 COT 2014
 * Generated source version: 2.7.10
 */

@XmlRootElement(name = "ListaPersonasResponse", namespace = "http://businessDelegateWS.presentation.usbcali.edu.co/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListaPersonasResponse", namespace = "http://businessDelegateWS.presentation.usbcali.edu.co/")

public class ListaPersonasResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

